import turtle

t = turtle.Turtle()
t3 = turtle.Turtle()
t3.hideturtle()
screen = turtle.Screen()
screen.setup(800,800)
screen.bgcolor("hot pink")
t.write("My presentation by Tara", font=("Arial", 24, "bold"), align="center")
turtle.addshape("tara.gif")
t3.penup()
t3.goto(0,100)
t3.shape("tara.gif")
a= t3.stamp()
turtle.addshape("santa.gif")
t3.penup()
t3.goto(225,100)
t3.shape("santa.gif")
a= t3.stamp()


t3.goto(0,0)
t.penup()
t.goto(50,-200)
t.pendown()
t.fillcolor("seagreen")
t.begin_fill()
t.circle(25)
t.end_fill()
t.penup()
t.goto(-100,100)


enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("sky blue")
t.penup()
t.goto(-100,-100)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.penup()
t.goto(-100,175)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 24, "bold"), align="center")
turtle.addshape("pizza.gif")
t3.shape("pizza.gif")
b = t3.stamp()
t3.goto(200,75)
turtle.addshape("cookie.gif")
t3.shape("cookie.gif")
c = t3.stamp()
t3.goto(80,80)
turtle.addshape("icecream.gif")
t3.shape("icecream.gif")
d = t3.stamp()
t.end_fill()

t.penup()
t.goto(200,-100)
t.write("Cookie", font=("Arial", 24, "bold"), align="center")
t.goto(200,-150)
t.write("pizza", font=("Arial", 24, "bold"), align="center")
t.goto(200,-200)
t.write("icecream", font=("Arial", 24, "bold"), align="center")
enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("Aquamarine")
t.penup()
t.goto(50,-100)
t.write("My Hobbies", font=("Arial", 24, "bold"), align="center")
turtle.addshape("cheer.gif")
t3.shape("cheer.gif")
e = t3.stamp()
t3.goto(-60,50)
turtle.addshape("cooking.gif")
t3.shape("cooking.gif")
f = t3.stamp()
t3.goto(-175,75)
turtle.addshape("colorguard.gif")
t3.shape("colorguard.gif")
g = t3.stamp()
t3.goto(135,20)
turtle.addshape("dance.gif")
t3.shape("dance.gif")
h = t3.stamp()
t.penup()
t.goto(-150,-150)
t.pendown()
t.fillcolor("cyan")
t.begin_fill()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()

t.penup()
t.goto(200,-100)
t.write("Cheer", font=("Arial", 24, "bold"), align="center")
t.goto(200,-150)
t.write("Cooking", font=("Arial", 24, "bold"), align="center")
t.goto(200,-200)
t.write("Colorguard", font=("Arial", 24, "bold"), align="center")
t.goto(200,-250)
t.write("Dance", font=("Arial", 24, "bold"), align="center")

enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("green")
t.penup()
t.goto(-100,175)
t.pendown()
t.write("Favorite Movie", font=("Arial", 24, "bold"), align="center")
t.penup()
t.goto(110,100)
turtle.addshape("peppapig.gif")
t3.penup()
t3.goto(0,100)
t3.shape("peppapig.gif")
a = t3.stamp()
t3.goto(0,100)
t.penup()
turtle.addshape("meangirls.gif")
t3.goto(90,100)
t3.shape("meangirls.gif")
i = t3.stamp()
t.goto(-25,15)
t.pendown()
t.fillcolor("Yellow")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(25)
t.left(90)
t.forward(50)
t.left(90)
t.forward(25)
t.left(90)
t.end_fill()
t.penup()
t.goto(200,-100)
t.write("Mean Girls", font=("Arial", 24, "bold"), align="center")
t.goto(200,-150)
t.write("Peppa Pig", font=("Arial", 24, "bold"), align="center")

enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("Orange")
t3.goto(180,-65)
t.penup()
t.goto(-100,175)
t.pendown()
t.write("Favorite Sport", font=("Arial", 24, "bold"), align="center")
turtle.addshape("soccer.gif")
t3.penup()
t3.goto(-50,-65)
t3.shape("soccer.gif")
a= t3.stamp()
t3.goto(-150,-65)
t3.goto(150,-65)
turtle.addshape("basketball.gif")
t3.shape("basketball.gif")
i = t3.stamp()
t.penup()
t.goto(-15,75)
t.pendown()
t.fillcolor("light pink")
t.begin_fill()
t.setheading(45)
t.forward(50)
t.setheading(135)
t.forward(50)
t.setheading(270)
t.forward(75)
t.end_fill()
t.penup()
t.goto(200,200)
t.write("Basketball", font=("Arial", 24, "bold"), align="center")
t.goto(200,150)
t.write("Soccer", font=("Arial", 24, "bold"), align="center")

turtle.done()
